# if else

In [ ]:
a = 4

In [ ]:
if a==a:
    print('pass')

print("pass")
    

In [ ]:
if a!=a:
    print('pass')

print("pass")

In [ ]:
if a!=a:
    print('pass')

    print("pass")

In [ ]:
if a%2 ==0:
    print('Even')
else:
    print('odd')

# elif

In [ ]:
a =6

In [ ]:
if a>5:
    if a %2 ==0:
        print('even')
    else :
        print('odd')
    print("10")
elif a <5:
    print("0")
else :
    print('5')

In [ ]:
var = int(input())

In [ ]:
var

# range

In [ ]:
range(1,10,1)

# for loop

In [ ]:
for i in range(5):
    print(i)

In [ ]:
for i in [1,2,3,4,5]:
    print(i+1)

In [ ]:
l1 = [1,2,3,4,5]

In [ ]:
len(l1)

In [ ]:
l1 = [10,20,30,40,50]

In [ ]:
len(l1)

In [ ]:
for i in l1:
    print(i)

In [ ]:
for i in range(len(l1)):
    print(l1[i])

# while loop

In [2]:
i= 0 

while i <50:
    print(i)
    i=i+10

0
10
20
30
40


# user define functionm

In [16]:
def func1(b,c,a=10):
    print(b,c,a)

In [23]:
func1(3,4,a=3)

3 4 3


In [22]:
func1(a=2,4,5)

5 4 2


In [24]:
def func2(a,b):
    return a+b

In [29]:
c = func2(4,5)
func1(3,4,5)
print(c)

3 4 5
9


# list comprehense

In [26]:
no = 7

In [27]:
print('Even') if  no % 2 == 0 else print('Odd')

Odd


In [28]:
print( 'Grt') if no > 5 else print('sml')

Grt


In [31]:
print('Even') if  no % 2 == 0 else print( 'Grt') if no > 5 else print('sml')

Grt


# lambda function

In [32]:
l1 = [1,2,3,4,5,6]

In [33]:
lambda x: x%2==0 ,l1

(<function __main__.<lambda>(x)>, [1, 2, 3, 4, 5, 6])

In [39]:
l3 =list(filter(lambda x: x%2==0 ,l1))
l3

[2, 4, 6]

In [38]:
l2 = []
for i in l1:
    if i %2==0:
       l2.append(i)
    
print(l2)

[2, 4, 6]


In [40]:
l3 =list(map(lambda x: x%2==0 ,l1))

In [41]:
l3

[False, True, False, True, False, True]

In [42]:
l1

[1, 2, 3, 4, 5, 6]

In [44]:
list(map(lambda x: x>3 ,l1))

[False, False, False, True, True, True]

# method and attribute

In [45]:
l1

[1, 2, 3, 4, 5, 6]

In [46]:
l1.append(8)

In [47]:
l1

[1, 2, 3, 4, 5, 6, 8]

In [48]:
l1.pop()

8

In [49]:
l1

[1, 2, 3, 4, 5, 6]

In [71]:
print(list())

[]


# NUmpy

In [63]:
import numpy as np

In [66]:
np.mean(l1)

3.5

In [67]:
r = np.array([1,3,4,56,7])

In [68]:
r

array([ 1,  3,  4, 56,  7])

In [70]:
r2 = np.array([3,4,5,6])

In [76]:
np.random.rand(3,2)

array([[0.65072359, 0.772307  ],
       [0.52445758, 0.97110441],
       [0.78888648, 0.97593365]])

In [79]:
np.linspace(1,10,num=50, endpoint=False)

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])