# NUMPY

In [20]:
import numpy as np

In [22]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [27]:
a = np.zeros((2,3))

In [28]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
a.shape

(2, 3)

In [30]:
a.size

6

In [31]:
a.nbytes

48

In [35]:
np.zeros((2,3),dtype='int').dtype

dtype('int32')

In [33]:
a.ndim

2

In [34]:
a.dtype

dtype('float64')

In [36]:
a.T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
b = np.ones((2,3),dtype='int')

In [40]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
c = np.full((2,3),10)

In [43]:
c

array([[10, 10, 10],
       [10, 10, 10]])

In [44]:
arr = np.array([1,2,3,4])

In [45]:
l1 = [1,2,3,4]

In [46]:
arr

array([1, 2, 3, 4])

In [47]:
l1

[1, 2, 3, 4]

In [48]:
for i in arr:
    print(i)

1
2
3
4


In [49]:
for i in l1:
    print(i)

1
2
3
4


In [50]:
# brodcasting

In [51]:
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [52]:
for i in range(len(l1)):
    l1[i] = l1[i] +2

In [53]:
l1

[3, 4, 5, 6]

In [54]:
arr + 2

array([3, 4, 5, 6])

In [58]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [95]:
np.linspace(10,100,8).reshape((4,2))

array([[ 10.        ,  22.85714286],
       [ 35.71428571,  48.57142857],
       [ 61.42857143,  74.28571429],
       [ 87.14285714, 100.        ]])

In [71]:
a = np.array([[1,2],[2,3]])

In [72]:
type(a)

numpy.ndarray

In [73]:
a

array([[1, 2],
       [2, 3]])

In [98]:
(np.random.random(40))

array([0.20984638, 0.77399422, 0.5595691 , 0.76780416, 0.61059018,
       0.42006983, 0.31476754, 0.76647827, 0.36835022, 0.454145  ,
       0.29344395, 0.07901938, 0.33573721, 0.15252958, 0.54942328,
       0.29910698, 0.70814116, 0.49738758, 0.59626444, 0.4095237 ,
       0.88203722, 0.74127774, 0.25871884, 0.3483951 , 0.18202858,
       0.95651498, 0.78546644, 0.40731016, 0.32168784, 0.31389735,
       0.37222057, 0.8181299 , 0.82491566, 0.83990248, 0.59991561,
       0.90494364, 0.80979844, 0.64994629, 0.75445022, 0.58156938])

In [81]:
np.random.randint(1,20,50)

array([ 7, 15, 10,  8,  5, 13, 16,  1,  5,  2, 10,  1,  3, 19, 19, 18,  4,
       16, 10, 15, 11, 19, 15, 14, 14, 15,  4, 10, 18, 15,  4, 12, 17,  1,
       19,  1, 13, 19, 17, 17,  7,  7, 11,  5,  7,  7, 14,  4,  6,  9])

In [83]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
x = np.arange(9)

In [85]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
x = x.reshape((3,3))

In [89]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.diag(x)

array([0, 4, 8])

In [3]:
import numpy as np

In [7]:
a1 = np.random.randint(1,10,9).reshape((3,3))

In [8]:
a1

array([[3, 6, 1],
       [8, 3, 2],
       [5, 7, 6]])

In [9]:
a2 = np.random.randint(1,10,16).reshape((4,4))

In [10]:
a2

array([[6, 5, 2, 3],
       [7, 1, 4, 5],
       [8, 3, 2, 8],
       [2, 6, 3, 4]])

In [11]:
a3 = np.random.randint(1,10,12).reshape((3,4))

In [12]:
a3

array([[3, 9, 4, 7],
       [6, 5, 7, 9],
       [6, 3, 2, 4]])

In [14]:
np.vstack((a3,a2))

array([[3, 9, 4, 7],
       [6, 5, 7, 9],
       [6, 3, 2, 4],
       [6, 5, 2, 3],
       [7, 1, 4, 5],
       [8, 3, 2, 8],
       [2, 6, 3, 4]])

In [15]:
np.hstack((a1,a3))

array([[3, 6, 1, 3, 9, 4, 7],
       [8, 3, 2, 6, 5, 7, 9],
       [5, 7, 6, 6, 3, 2, 4]])

# index and slicing, broadcasting

In [16]:
a1 = np.random.randint(1,100,9).reshape((3,3))

In [17]:
a1

array([[ 2, 85, 80],
       [64, 81, 81],
       [ 7, 54, 31]])

In [19]:
sum(a1)

array([ 73, 220, 192])

In [22]:
np.sum(a1, axis = 0)

array([ 73, 220, 192])

In [25]:
np.mean(a1, axis =1 )

array([55.66666667, 75.33333333, 30.66666667])

In [26]:
np.median(a1)

64.0

In [27]:
np.median(a1,axis=1)

array([80., 81., 31.])

In [28]:
a1 +2

array([[ 4, 87, 82],
       [66, 83, 83],
       [ 9, 56, 33]])

In [ ]:
a1[:,:]

In [29]:
l1 = [1,2,3,4]

In [30]:
l1[0]

1

In [31]:
l1[-1]

4

In [33]:
a1

array([[ 2, 85, 80],
       [64, 81, 81],
       [ 7, 54, 31]])

In [32]:
a1[1,1]

81

In [34]:
a1[-1,-1]

31

In [35]:
a1[1,2]

81

In [36]:
a1[-1,-2]

54

In [37]:
a1[2,1]

54

In [38]:
a1[1,1] = 100

In [39]:
a1

array([[  2,  85,  80],
       [ 64, 100,  81],
       [  7,  54,  31]])

In [40]:
l1

[1, 2, 3, 4]

In [43]:
l1[1:3]

[2, 3]

In [48]:
a1[0:1,]

array([[ 2, 85, 80]])

In [50]:
a1[2:3,]

array([[ 7, 54, 31]])

In [52]:
a1[2:4,]

array([[ 7, 54, 31]])

In [54]:
a1[,]

array([], shape=(0, 3), dtype=int32)

In [55]:
a1[1:2,0:2]

array([[ 64, 100]])

In [56]:
a1

array([[  2,  85,  80],
       [ 64, 100,  81],
       [  7,  54,  31]])

In [57]:
a1[2:2,0:2]  # sarum.

array([], shape=(0, 2), dtype=int32)

In [58]:
a1[2:2,:]

array([], shape=(0, 3), dtype=int32)

In [61]:
a1[0,0]

2

In [60]:
a1[0:1,0:1]

array([[2]])

In [64]:
a1

array([[  2,  85,  80],
       [ 64, 100,  81],
       [  7,  54,  31]])

In [63]:
a1[0:1,0:2]

array([[ 2, 85]])

In [66]:
a1[0:1,1:3]

array([[85, 80]])

In [67]:
a1[1:2,2:3]

array([[81]])

In [68]:
a1[2:3,2:3]

array([[31]])

In [69]:
a1[1:3,]

array([[ 64, 100,  81],
       [  7,  54,  31]])

In [70]:
a1[1:3,2:3]

array([[81],
       [31]])

In [71]:
a1[1:3,1:2]

array([[100],
       [ 54]])

In [72]:
a1

array([[  2,  85,  80],
       [ 64, 100,  81],
       [  7,  54,  31]])

In [77]:
a1[1:2,].ndim  # slicing

2

In [78]:
a1[2,].ndim  # indexing

1

In [80]:
a1[1:3,1:2]

array([[100],
       [ 54]])

In [84]:
a1[a1 > 50]

array([ 85,  80,  64, 100,  81,  54])

In [86]:
np.mean(a1)

56.0

In [87]:
a1 > np.mean(a1)

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [85]:
a1[ a1 > np.mean(a1)]

array([ 85,  80,  64, 100,  81])